@startuml
start 
    :Надіслати запит на сервер;
      note left: Для отримання\n всіх ID працівників
    if(Прийшла відповідь?) then (Ні)
     :Вивід повідомлення про збій;
    stop
    else (Так)   
    endif   
        if(Відповідь == Успішно?) then (Так)
        :ID <
         note left: Ввід ID працівника\nабо вибрати із випадаючого списку
        
    :Ввід часу < 
    note left: Ввід часу працівника\nколи зайшов \ вийшов із роботи
    :Операції зайшов/вийшов;
      note left: Вибір операції\n чи працівник\n зайшов/вийшов із роботи
    else (Ні)
    :Вивести повідомлення\n про помилку в \nотриманні ID працівників> 
    stop
   endif  
    :Надіслати запит серверу;
     note right: Надсилання даних\n про працівника
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    if(Відповідь == Успішно?) then (Так)
    :Дані успішно занесені>
    else (Ні)
    :Вивести повідомлення\n про помилку в \nзанесенні даних \nпро працівника>
    endif

stop
@enduml
