@startuml
left to right direction

actor "Сервер" as server 
rectangle "Сервер" {
  usecase "Обробка запиту" as UC1
  usecase "Перевірка\n правильності\nотриманого пакету" as UC2
  usecase "Декодування\n команди прийнятої\n від клієнта" as UC3

}

rectangle "База даних"{
    usecase "Запис даних"  as BD1
    usecase "Створення таблиці"  as BD2
    usecase "Зчитування даних\n із таблиці" as BD3
    usecase "Пошук даних" as BD4
    usecase "Видалення запису із таблиці"  as BD5
}


server -->  UC2
UC2 --> UC1
UC1   --> UC3

UC3  -->  BD1
UC3  -->  BD2
UC3  -->  BD3
UC3  -->  BD4
UC3  -->  BD5


@endum