@startuml add_payment_date
start 
    :Отримання запросу від адміна<
    :Запис працівника у БД;
    note right: Запис імені у БД\nЗапис прізвища у БД\nЗапис по-батькові у БД\nЗапис посади БД\nЗапис ціни оплати у БД\n за годину у БД
    if(Запис успішний?) then (Так)
     :Надіслати повідомлення,\n що дані добавлені;
     else (Ні)
     :Надіслати повідомлення\nпро помилку запису даних;
     endif
stop
@enduml

