@startuml add_payment_date
start 
    :Отримання запросу адміна;

    :Зберегти дату у БД;
    
     if(Дані збережено?) then (Так)
         :Відправити повідомлення\n що дані успішно збережено>
    else (Ні) 
        :Відправити повідомлення\n що збереження не вдалося>
    endif
stop
@enduml

