@startuml
start 
    :Отримання запиту адміна;
    :Запис відвудуваності у БД;
    note left: Запис ID працівника у БД\nЗапис дати у БД\nЗапис статусу "зайшов/вийшов" у БД
     if(Запис успішний?) then (Так)
     :Надіслати повідомлення,\n що дані добавлені;
     else (Ні)
     :Надіслати повідомлення\nпро помилку запису даних;
     endif
stop
@enduml
