@startuml
start 
    :Отримання запиту; 
    note left: Запрос від емулятора \nсканера RFID карти на отримання\nID усіх працівників
    :Пошук в БД ID всіх працівників;
    :Надіслати пакет даних із \nсписком усіх ID працівників;
    :Отримання запиту; 
    note left: Запит від сканера \nRFID карти \nдля запису даних
    :Запис відвудуваності у БД;
    note left: Запис ID працівника у БД\nЗапис дати у БД\nЗапис статусу "зайшов/вийшов" у БД
     if(Запис успішний?) then (Так)
     :Надіслати повідомлення,\n що дані добавлені;
     else (Ні)
     :Надіслати повідомлення\nпро помилку запису даних;
     endif
stop
@enduml
