@startuml
start 
    :Отримання логіну та паролю адміна;
    if(Є логін у базі даних?) then (Так)
      else (Ні) 
    :Надіслати повідомення \nщо вхід не виконаний;
endif
         if(Є пароль у базі даних?) then (Так)
            :Відмітити даного користувача, \nтаблиці авторизованих \nкористувачів;
            :Надіслати повідомення \nщо вхід успішно виконаний;
            :Надіслати унікальне ID користувача;
         
    else (Ні)
    :Надіслати повідомення \nщо вхід не виконаний;
endif
stop
@enduml
