@startuml get_report
skinparam conditionStyle diamond
start 
    :Отримання запросу адміна<
    if( ) then (Звітність одного працівника)
    if(Є виплати даному працівнику?) then (Так)
    :Відправити\n всі\nзнайдені виплати\n для працівника із БД >
    else (Ні)
    :Відправити\n повідомлення що\n виплат для працівника\n не знайдено >
    endif
    else (Звітність усіх працівників)
        
        if(Є виплати по заданому переіоду? ) then (Так)
       
         :Відправити\n перелік усіх \nзнайдених виплат\n за період із БД>
         else (Ні)
         :Відправити\n повідомлення що\n виплат із заданого\n періоду не знайдено >
         endif
    endif
stop
@enduml
