@startuml pay_on_demand
start 
    :Отримання запросу\n адміністратора <
    :Перевірка чи можливе нарахування;
    note left: Перевірка в БД\nчи вже була оплата\nза даний період \n
if(Нарахування можливе?) then (Ні)
:Відправити повідомлення \nщо нарахування коштів \nне можливе >
else (Так)
    :Порахувати суму виплати |

    :Запис даних виплати у БД;
    note right: Запис ID користувача у БД\nЗапис виплаченої суми у БД\nЗапис з якого числа виплата у БД\nЗапис по яке число здійснена оплата у БД\n
    if(Запис успішний?) then (Так)
     :Відправити повідомлення\n що кошти\nуспішно нараховано >
     else (Ні)
     :Надіслати повідомлення\nпро помилку запису даних;
     endif

endif
stop
@enduml
