@startuml add_payment_date
start 
    :Зчитати із БД дату оплати;

    :Отримати поточну дату від ОС;
    :Порахувати різницю\nміж датою оплати\n та датою від ОС| 
note left: Порахована різниця\nотримується в\nмілісекундах\nі передається як\nпараметр в таймер
fork
:Запустити таймер |
note left: Таймер запускається\n в окремому потоці
label 10

fork again
while (Дата оплати настала?) is (Так)

repeat 
:Зчитати дані про працівника з таблиці;
:Порахувати суму яку потрібно виплатити |
:Здійснити виплату |
note right: Запис ID користувача у БД\nЗапис виплаченої суми у БД\nЗапис з якого числа виплата у БД\nЗапис по яке число здійснена оплата у БД\n


repeat while(Всі працівники прочитані?) is (Ні) not (Так)
:Обчислення наступної\n дати для виплати|
:Запис наступної \nдати виплати в БД ;
endwhile (Ні)
:Залитися в ціклі поки \nне настане дата виплати;
end fork

@enduml

