@startuml get_report
skinparam conditionStyle diamond
start 
    :Отримання запросу адміна< 
    note right: Запит на пошук всієї \nісторії виплат по періодам
    if (Є з'єднання із БД?) then (Так)
    :Пошук в БД всіх виплат;
      if(Є історія виплат?) then (Так)
      :Відправити всі знайдені \nзаписи періодів виплат;
    else (Ні)
    :Відправити\n повідомлення що\n виплат не знайдено >
    endif
    :Отримання запросу адміна<
    note right: Отримання періоду виплати
    :Пошук в БД детальної \nінформації виплат \nпо отриманому періоду;
    :Відправити всі знайдені записи;
    else (Ні)
    :Надіслати повідомлення, \nщо зв'язок із БД неможливий;
    endif

stop
@enduml
