@startuml search
skinparam conditionStyle diamond
start 
    :Отримання запросу адміна<
    if (Є з'єднання із БД?) then (Так)
        :Пошук в БД записів \nпо зданому ключовому слову;
            note left: Ключове слово: \nID або ім'я працівника
                if (Є співпадіння в БД? ) then (Так)
                    :Відправити всі знайдені записи;
                else (Ні)
                    :Відправити повідомлення, \nщо записів по заданому \nключовому слову \nне знайдено;
                endif
    else (Ні)
        :Надіслати повідомлення, \nщо зв'язок із БД неможливий;
    endif
   stop
@enduml
