@startuml add_payment_date
start 
    :Введіть дату \nнарахування зарплати <
    note right: Кількість днів через \nякі буде нараховуватися зарплата
    :Надіслати запит серверу;
     note left: Зберегти дані\nв таблицю SystemSetting
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
    if(Відповідь == Успішно?) then (Так)
    :Дані успішно збережено>
    :Вивести дату коли буде нарахування>
    else (Ні)
    :Вивести повідомлення\n про помилку\n в збереженні даних>
    endif
stop
@enduml

