@startuml
start 
    :Ввід даних працівника < 
    note left: Ввід імені\nВвід прізвища\nВвід по - батькові\nВвід посади\nВвід ціни оплати за годину\nВвід номера карти
    :Надіслати запит серверу;
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
    if(Відповідь == Успішно?) then (Так)
    :Працівник успішно доданий>
    else (Ні)
    :Вивід повідомлення\n про помилку\n при додаванні працівника>
    endif
    stop
@enduml
