@startuml
start 
note left: Адмін вже є зареєстрований
repeat 
    :Ввід даних\n для авторизації;
    note left: Ввід логіну та паролю
    :Надіслати запит серверу;
    if(Прийшла відповідь?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
    backward :Логін або пароль\n не вірний;
repeat while(Користувач є в системі?) is (Ні) not (Так)
:(Вхід в систему успішний);
stop
note right: Доступ до внутрішнього функціоналу
@enduml
