@startuml
start 
    if(Отримати звітність для одного працівника?) then (Так)
    :Введіть ID працівника <
    note left : Вся історія виплати\nдля працівника
    :Надіслати запит серверу;
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так)
    endif
    else (Ні)
    :Отримати звітність усіх працівників;
    note right: Історія виплат за певний\nперіод для усіх працівників
:Вибрати період з - по>
:Надіслати запит серверу;
  if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так)

    endif
endif
 if(Відповідь == Успішно?) then (Так)
    :Відобразити звітність > 
    else (Ні)
    :Вивести повідомлення\n про помилку\n отримання звітності>
    endif
stop
@enduml
