@startuml
start 
    :Вихід із системи;
    :Надсилання запиту на сервер >
    if(Прийшла відповідь?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    if(Дійсно хочете вийти?) then (Так)
    else (Ні)
    :Повернення до головного меню;
    endif
    endif
stop
@enduml
