@startuml pay_on_demand
start 
    :Надіслати запит \nна отримання списку \nID працівників; 
    :Вибрати ID із отриманого списку< 
    :Вибрати період за який \nнарахувати зарплату;
    :Надіслати запит серверу;
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
if(Відповідь == успіх?) then (Ні)
:Неможливо нарахувати \nзарплату за даний період >
else (Так)
:Заробітну плату \nуспішно нараховано >
endif
stop
@enduml
