@startuml
start 
:Ввід ID працівника<
:Ввід даних хвороби <
note right: 1)Яка хвороба?\n2)Номер лікарняного\n3)З якого - по яке число лікарняний
:Надіслати запит серверу;
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
    if(Відповідь == Успішно?) then (Так)
    :Дані успішно збережено>
    else (Ні)
    :Вивести повідомлення\n про помилку\n в збереженні даних>
    endif
@enduml
