@startuml
start
:Надіслати запит серверу;
note right: Отримати історію періодів виплат, наприклад\n(Description -> 09/10/2022 - 09/23/2022 \n Total debited -> $30,093.45)
if(Прийшла відповідь ?) then (Ні)
  :Вивід повідомлення про збій;
  stop
else (Так)
  if(Відповідь == Успішно?) then (Так)
    :Відобразити історію періодів виплат>
    :Вибрати один із отриманих періодів;
    :Надіслати запит серверу;
    note right: Отримати детальну звітність\n виплати по заданому періоду\n(Employees, Total Hours,\n Employee Taxes, Gross Earnings, Net Pay)
    if(Прийшла відповідь ?) then (Ні)
      :Вивід повідомлення про збій;
      stop
    else (Так)
      if(Відповідь == Успішно?) then (Так)
        :Відобразити детальну історію виплати>
          else (Ні)
      :Вивести повідомлення\n про помилку\n отримання детальної\nісторії виплат>
      endif
      endif
    else (Ні)
      :Вивести повідомлення\n про помилку\n отримання історії виплат>
    endif





  endif
  stop
  @enduml
