@startuml
start 
 :Введіть ім'я або ID \nпрацівника < 
 :Надіслати запит серверу;
    if(Прийшла відповідь ?) then (Ні)
    :Вивід повідомлення про збій;
    stop
    else (Так) 
    endif
    if(Відповідь == Успішно?) then (Так)
    :Відобразити всі дані \nпо введеному \nключовому слову>
    else (Ні)
    :Вивід повідомлення\n про помилку\n при пошуку даних\n працівника>
    endif
    stop

@enduml
